version: "2.0"
services:
  ruby:
    image: ruby:3.1.0-preview1-slim-bullseye
    volumes:
    - /etc/group:/etc/group:ro
    - /etc/passwd:/etc/passwd:ro
    - .:/app
    working_dir: /app
    environment:
      BUNDLE_PATH: /app/.bundle
      RUBYOPT: -EUTF-8
    entrypoint:
    - bundle
    - exec
    - bin/dl.rb
